default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: goal_tracker_development

test:
  <<: *default
  database: goal_tracker_test

production:
  <<: *default
  database: goal_tracker_production
  username: goal_tracker
  password: <%= ENV['GOAL_TRACKER_DATABASE_PASSWORD'] %>